export const mockWeatherData = [
  {
    region: "Noord-Holland",
    days: [
      {
        date: "2023-10-01",
        mintemperature: 15,
        maxtemperature: 20,
        iconcode: "sunny",
        windspeedms: 10,
        winddirectiondegrees: 90,
        winddirection: "O",
        beaufort: 4,
        precipitation: 0,
        uvindex: 6,
        waveheight: 0.7,
        wavedirection: 270,
        seawatertemperature: 10.4,
        lowtide: ["04:45", "17:15"],
        hightide: ["11:00", "23:30"],
        alert_jellyfish: "True",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-02",
        mintemperature: 14,
        maxtemperature: 19,
        iconcode: "cloudy",
        windspeedms: 12,
        winddirectiondegrees: 100,
        winddirection: "O",
        beaufort: 5,
        precipitation: 0.2,
        uvindex: 5,
        waveheight: 0.8,
        wavedirection: 275,
        seawatertemperature: 10.2,
        lowtide: ["05:30", "18:00"],
        hightide: ["11:45", "00:15"],
        alert_jellyfish: "True",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-03",
        mintemperature: 13,
        maxtemperature: 17,
        iconcode: "rainy",
        windspeedms: 15,
        winddirectiondegrees: 110,
        winddirection: "OZO",
        beaufort: 6,
        precipitation: 3.5,
        uvindex: 3,
        waveheight: 1.2,
        wavedirection: 280,
        seawatertemperature: 10.0,
        lowtide: ["06:15", "18:45"],
        hightide: ["12:30", "01:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-04",
        mintemperature: 12,
        maxtemperature: 16,
        iconcode: "rainy",
        windspeedms: 18,
        winddirectiondegrees: 120,
        winddirection: "ZO",
        beaufort: 7,
        precipitation: 5.0,
        uvindex: 2,
        waveheight: 1.5,
        wavedirection: 285,
        seawatertemperature: 9.8,
        lowtide: ["07:00", "19:30"],
        hightide: ["13:15", "01:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-05",
        mintemperature: 13,
        maxtemperature: 18,
        iconcode: "cloudy",
        windspeedms: 14,
        winddirectiondegrees: 130,
        winddirection: "ZO",
        beaufort: 6,
        precipitation: 1.0,
        uvindex: 4,
        waveheight: 1.0,
        wavedirection: 270,
        seawatertemperature: 9.9,
        lowtide: ["07:45", "20:15"],
        hightide: ["14:00", "02:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-06",
        mintemperature: 14,
        maxtemperature: 19,
        iconcode: "cloudy",
        windspeedms: 10,
        winddirectiondegrees: 140,
        winddirection: "ZO",
        beaufort: 4,
        precipitation: 0.5,
        uvindex: 5,
        waveheight: 0.7,
        wavedirection: 265,
        seawatertemperature: 10.1,
        lowtide: ["08:30", "21:00"],
        hightide: ["14:45", "03:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-07",
        mintemperature: 15,
        maxtemperature: 21,
        iconcode: "sunny",
        windspeedms: 8,
        winddirectiondegrees: 150,
        winddirection: "ZZO",
        beaufort: 3,
        precipitation: 0,
        uvindex: 6,
        waveheight: 0.5,
        wavedirection: 260,
        seawatertemperature: 10.3,
        lowtide: ["09:15", "21:45"],
        hightide: ["15:30", "04:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
    ],
  },
  {
    region: "Zuid-Holland",
    days: [
      {
        date: "2023-10-01",
        mintemperature: 16,
        maxtemperature: 21,
        iconcode: "cloudy",
        windspeedms: 12,
        winddirectiondegrees: 100,
        winddirection: "O",
        beaufort: 5,
        precipitation: 0.2,
        uvindex: 5,
        waveheight: 0.9,
        wavedirection: 280,
        seawatertemperature: 11.2,
        lowtide: ["05:15", "17:45"],
        hightide: ["11:30", "00:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-02",
        mintemperature: 15,
        maxtemperature: 20,
        iconcode: "cloudy",
        windspeedms: 14,
        winddirectiondegrees: 110,
        winddirection: "OZO",
        beaufort: 6,
        precipitation: 0.5,
        uvindex: 4,
        waveheight: 1.0,
        wavedirection: 285,
        seawatertemperature: 11.0,
        lowtide: ["06:00", "18:30"],
        hightide: ["12:15", "00:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-03",
        mintemperature: 14,
        maxtemperature: 18,
        iconcode: "rainy",
        windspeedms: 16,
        winddirectiondegrees: 120,
        winddirection: "ZO",
        beaufort: 6,
        precipitation: 4.0,
        uvindex: 3,
        waveheight: 1.3,
        wavedirection: 290,
        seawatertemperature: 10.8,
        lowtide: ["06:45", "19:15"],
        hightide: ["13:00", "01:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-04",
        mintemperature: 13,
        maxtemperature: 17,
        iconcode: "rainy",
        windspeedms: 19,
        winddirectiondegrees: 130,
        winddirection: "ZO",
        beaufort: 7,
        precipitation: 5.5,
        uvindex: 2,
        waveheight: 1.6,
        wavedirection: 295,
        seawatertemperature: 10.6,
        lowtide: ["07:30", "20:00"],
        hightide: ["13:45", "02:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-05",
        mintemperature: 14,
        maxtemperature: 19,
        iconcode: "cloudy",
        windspeedms: 15,
        winddirectiondegrees: 140,
        winddirection: "ZO",
        beaufort: 6,
        precipitation: 1.5,
        uvindex: 4,
        waveheight: 1.1,
        wavedirection: 280,
        seawatertemperature: 10.7,
        lowtide: ["08:15", "20:45"],
        hightide: ["14:30", "03:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-06",
        mintemperature: 15,
        maxtemperature: 20,
        iconcode: "cloudy",
        windspeedms: 11,
        winddirectiondegrees: 150,
        winddirection: "ZZO",
        beaufort: 4,
        precipitation: 0.3,
        uvindex: 5,
        waveheight: 0.8,
        wavedirection: 275,
        seawatertemperature: 10.9,
        lowtide: ["09:00", "21:30"],
        hightide: ["15:15", "03:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-07",
        mintemperature: 16,
        maxtemperature: 22,
        iconcode: "sunny",
        windspeedms: 9,
        winddirectiondegrees: 160,
        winddirection: "ZZO",
        beaufort: 3,
        precipitation: 0,
        uvindex: 6,
        waveheight: 0.6,
        wavedirection: 270,
        seawatertemperature: 11.1,
        lowtide: ["09:45", "22:15"],
        hightide: ["16:00", "04:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
    ],
  },
  {
    region: "Zeeland",
    days: [
      {
        date: "2023-10-01",
        mintemperature: 17,
        maxtemperature: 22,
        iconcode: "sunny",
        windspeedms: 8,
        winddirectiondegrees: 110,
        winddirection: "OZO",
        beaufort: 4,
        precipitation: 0,
        uvindex: 7,
        waveheight: 0.5,
        wavedirection: 260,
        seawatertemperature: 12.0,
        lowtide: ["04:30", "16:45"],
        hightide: ["10:30", "22:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-02",
        mintemperature: 16,
        maxtemperature: 21,
        iconcode: "sunny",
        windspeedms: 10,
        winddirectiondegrees: 120,
        winddirection: "ZO",
        beaufort: 4,
        precipitation: 0,
        uvindex: 6,
        waveheight: 0.6,
        wavedirection: 265,
        seawatertemperature: 11.8,
        lowtide: ["05:15", "17:30"],
        hightide: ["11:15", "23:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-03",
        mintemperature: 15,
        maxtemperature: 20,
        iconcode: "cloudy",
        windspeedms: 12,
        winddirectiondegrees: 130,
        winddirection: "ZO",
        beaufort: 5,
        precipitation: 0.5,
        uvindex: 5,
        waveheight: 0.8,
        wavedirection: 270,
        seawatertemperature: 11.6,
        lowtide: ["06:00", "18:15"],
        hightide: ["12:00", "00:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-04",
        mintemperature: 14,
        maxtemperature: 19,
        iconcode: "rainy",
        windspeedms: 15,
        winddirectiondegrees: 140,
        winddirection: "ZO",
        beaufort: 6,
        precipitation: 3.0,
        uvindex: 3,
        waveheight: 1.0,
        wavedirection: 275,
        seawatertemperature: 11.4,
        lowtide: ["06:45", "19:00"],
        hightide: ["12:45", "01:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-05",
        mintemperature: 15,
        maxtemperature: 20,
        iconcode: "cloudy",
        windspeedms: 13,
        winddirectiondegrees: 150,
        winddirection: "ZZO",
        beaufort: 5,
        precipitation: 1.0,
        uvindex: 4,
        waveheight: 0.9,
        wavedirection: 270,
        seawatertemperature: 11.5,
        lowtide: ["07:30", "19:45"],
        hightide: ["13:30", "01:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-06",
        mintemperature: 16,
        maxtemperature: 21,
        iconcode: "sunny",
        windspeedms: 10,
        winddirectiondegrees: 160,
        winddirection: "ZZO",
        beaufort: 4,
        precipitation: 0,
        uvindex: 6,
        waveheight: 0.7,
        wavedirection: 265,
        seawatertemperature: 11.7,
        lowtide: ["08:15", "20:30"],
        hightide: ["14:15", "02:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-07",
        mintemperature: 17,
        maxtemperature: 23,
        iconcode: "sunny",
        windspeedms: 8,
        winddirectiondegrees: 170,
        winddirection: "Z",
        beaufort: 3,
        precipitation: 0,
        uvindex: 7,
        waveheight: 0.5,
        wavedirection: 260,
        seawatertemperature: 11.9,
        lowtide: ["09:00", "21:15"],
        hightide: ["15:00", "03:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
    ],
  },
  {
    region: "Waddeneilanden",
    days: [
      {
        date: "2023-10-01",
        mintemperature: 14,
        maxtemperature: 18,
        iconcode: "rainy",
        windspeedms: 15,
        winddirectiondegrees: 70,
        winddirection: "ONO",
        beaufort: 6,
        precipitation: 2.5,
        uvindex: 3,
        waveheight: 1.2,
        wavedirection: 290,
        seawatertemperature: 9.8,
        lowtide: ["05:00", "17:30"],
        hightide: ["11:15", "23:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-02",
        mintemperature: 13,
        maxtemperature: 17,
        iconcode: "rainy",
        windspeedms: 17,
        winddirectiondegrees: 80,
        winddirection: "O",
        beaufort: 7,
        precipitation: 3.0,
        uvindex: 2,
        waveheight: 1.4,
        wavedirection: 295,
        seawatertemperature: 9.6,
        lowtide: ["05:45", "18:15"],
        hightide: ["12:00", "00:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-03",
        mintemperature: 12,
        maxtemperature: 16,
        iconcode: "storm",
        windspeedms: 20,
        winddirectiondegrees: 90,
        winddirection: "O",
        beaufort: 8,
        precipitation: 6.0,
        uvindex: 1,
        waveheight: 1.8,
        wavedirection: 300,
        seawatertemperature: 9.4,
        lowtide: ["06:30", "19:00"],
        hightide: ["12:45", "01:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-04",
        mintemperature: 11,
        maxtemperature: 15,
        iconcode: "storm",
        windspeedms: 22,
        winddirectiondegrees: 100,
        winddirection: "O",
        beaufort: 9,
        precipitation: 8.0,
        uvindex: 1,
        waveheight: 2.0,
        wavedirection: 305,
        seawatertemperature: 9.2,
        lowtide: ["07:15", "19:45"],
        hightide: ["13:30", "02:00"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-05",
        mintemperature: 12,
        maxtemperature: 16,
        iconcode: "rainy",
        windspeedms: 18,
        winddirectiondegrees: 110,
        winddirection: "OZO",
        beaufort: 7,
        precipitation: 4.0,
        uvindex: 2,
        waveheight: 1.6,
        wavedirection: 300,
        seawatertemperature: 9.3,
        lowtide: ["08:00", "20:30"],
        hightide: ["14:15", "02:45"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "True",
        alert_ripcurrent: "True",
      },
      {
        date: "2023-10-06",
        mintemperature: 13,
        maxtemperature: 17,
        iconcode: "cloudy",
        windspeedms: 14,
        winddirectiondegrees: 120,
        winddirection: "ZO",
        beaufort: 6,
        precipitation: 1.0,
        uvindex: 3,
        waveheight: 1.2,
        wavedirection: 295,
        seawatertemperature: 9.5,
        lowtide: ["08:45", "21:15"],
        hightide: ["15:00", "03:30"],
        alert_jellyfish: "False",
        alert_floatingdevices: "True",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
      {
        date: "2023-10-07",
        mintemperature: 14,
        maxtemperature: 18,
        iconcode: "cloudy",
        windspeedms: 12,
        winddirectiondegrees: 130,
        winddirection: "ZO",
        beaufort: 5,
        precipitation: 0.5,
        uvindex: 4,
        waveheight: 1.0,
        wavedirection: 290,
        seawatertemperature: 9.7,
        lowtide: ["09:30", "22:00"],
        hightide: ["15:45", "04:15"],
        alert_jellyfish: "False",
        alert_floatingdevices: "False",
        alert_dangeroussea: "False",
        alert_ripcurrent: "False",
      },
    ],
  },
]
